# repo:     pxcs/pxc
# filename: FUNDING.YML
# don't want money ( doain aja biar gak dipolisikan )
# offensive cyber-attacks

open_collective: byt3n33dl3
custom: s.id/byt3n33dl3
patreon: byt3n33dl3
ko_fi: byt3n33dl3
