# repo:     pxcs/pxc
# filename: FUNDING.YML
# don't want money ( doain aja biar gak dipolisikan )
# offensive cyber-attacks

custom: s.id/byt3n33dl3
github: bytn33dl3
patreon: byt3n33dl3
ko_fi: byt3n33dl3
